// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import Claims from 'network-claims-optum';

const client = new Claims({
  apiKey: 'My API Key',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource v3', () => {
  // Prism tests are disabled
  test.skip('healthCheck', async () => {
    const responsePromise = client.medicalnetwork.professionalclaims.v3.healthCheck();
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('submitClaim: only required params', async () => {
    const responsePromise = client.medicalnetwork.professionalclaims.v3.submitClaim({
      billing: { providerType: 'BillingProvider' },
      claimInformation: {
        benefitsAssignmentCertificationIndicator: 'Y',
        claimChargeAmount: '28.75',
        claimFilingCode: 'CI',
        claimFrequencyCode: '1',
        healthCareCodeInformation: [{ diagnosisCode: 'diagnosisCode', diagnosisTypeCode: 'BK' }],
        patientControlNumber: '12345',
        placeOfServiceCode: '11',
        planParticipationCode: 'A',
        releaseInformationCode: 'Y',
        serviceLines: [
          {
            professionalService: {
              compositeDiagnosisCodePointers: { diagnosisCodePointers: ['string'] },
              lineItemChargeAmount: '25',
              measurementUnit: 'UN',
              procedureCode: 'E0570',
              procedureIdentifier: 'HC',
              serviceUnitCount: '1',
            },
            serviceDate: '20050514',
          },
        ],
        signatureIndicator: 'Y',
      },
      controlNumber: '000000001',
      receiver: { organizationName: 'EXTRA HEALTHY INSURANCE' },
      submitter: { contactInformation: { name: 'SUBMITTER CONTACT INFO' } },
      subscriber: { paymentResponsibilityLevelCode: 'P' },
    });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('submitClaim: required and optional params', async () => {
    const response = await client.medicalnetwork.professionalclaims.v3.submitClaim({
      billing: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      claimInformation: {
        benefitsAssignmentCertificationIndicator: 'Y',
        claimChargeAmount: '28.75',
        claimFilingCode: 'CI',
        claimFrequencyCode: '1',
        healthCareCodeInformation: [{ diagnosisCode: 'diagnosisCode', diagnosisTypeCode: 'BK' }],
        patientControlNumber: '12345',
        placeOfServiceCode: '11',
        planParticipationCode: 'A',
        releaseInformationCode: 'Y',
        serviceLines: [
          {
            professionalService: {
              compositeDiagnosisCodePointers: { diagnosisCodePointers: ['string'] },
              lineItemChargeAmount: '25',
              measurementUnit: 'UN',
              procedureCode: 'E0570',
              procedureIdentifier: 'HC',
              serviceUnitCount: '1',
              copayStatusCode: '0',
              description: 'description',
              emergencyIndicator: 'Y',
              epsdtIndicator: 'Y',
              familyPlanningIndicator: 'Y',
              placeOfServiceCode: 'placeOfServiceCode',
              procedureModifiers: ['string'],
            },
            serviceDate: '20050514',
            additionalNotes: 'additionalNotes',
            ambulanceCertification: [{ certificationConditionIndicator: 'N', conditionCodes: ['01'] }],
            ambulanceDropOffLocation: {
              address1: '123 address1',
              city: 'city1',
              address2: 'apt 000',
              countryCode: 'countryCode',
              countrySubDivisionCode: 'countrySubDivisionCode',
              postalCode: '981010000',
              state: 'wa',
            },
            ambulancePatientCount: 0,
            ambulancePickUpLocation: {
              address1: '123 address1',
              city: 'city1',
              address2: 'apt 000',
              countryCode: 'countryCode',
              countrySubDivisionCode: 'countrySubDivisionCode',
              postalCode: '981010000',
              state: 'wa',
            },
            ambulanceTransportInformation: {
              ambulanceTransportReasonCode: 'A',
              transportDistanceInMiles: 'transportDistanceInMiles',
              patientWeightInPounds: 'patientWeightInPounds',
              roundTripPurposeDescription: 'roundTripPurposeDescription',
              stretcherPurposeDescription: 'stretcherPurposeDescription',
            },
            assignedNumber: 'assignedNumber',
            conditionIndicatorDurableMedicalEquipment: {
              certificationConditionIndicator: 'Y',
              conditionIndicator: '38',
              conditionIndicatorCode: '38',
            },
            contractInformation: {
              contractTypeCode: '01',
              contractAmount: 'contractAmount',
              contractCode: 'contractCode',
              contractPercentage: 'contractPercentage',
              contractVersionIdentifier: 'contractVersionIdentifier',
              termsDiscountPercentage: 'termsDiscountPercentage',
            },
            drugIdentification: {
              measurementUnitCode: 'F2',
              nationalDrugCode: 'nationalDrugCode',
              nationalDrugUnitCount: 'nationalDrugUnitCount',
              serviceIdQualifier: 'EN',
              linkSequenceNumber: 'linkSequenceNumber',
              pharmacyPrescriptionNumber: 'pharmacyPrescriptionNumber',
            },
            durableMedicalEquipmentCertificateOfMedicalNecessity: { attachmentTransmissionCode: 'AB' },
            durableMedicalEquipmentCertification: {
              certificationTypeCode: 'I',
              durableMedicalEquipmentDurationInMonths: 'durableMedicalEquipmentDurationInMonths',
            },
            durableMedicalEquipmentService: {
              days: 'days',
              frequencyCode: '1',
              purchasePrice: 'purchasePrice',
              rentalPrice: 'rentalPrice',
            },
            fileInformation: ['string'],
            formIdentification: [
              {
                formIdentifier: 'formIdentifier',
                formTypeCode: 'AS',
                supportingDocumentation: [
                  {
                    questionNumber: 'questionNumber',
                    questionResponse: 'questionResponse',
                    questionResponseAsDate: 'questionResponseAsDate',
                    questionResponseAsPercent: 'questionResponseAsPercent',
                    questionResponseCode: 'N',
                  },
                ],
              },
            ],
            goalRehabOrDischargePlans: 'goalRehabOrDischargePlans',
            hospiceEmployeeIndicator: true,
            lineAdjudicationInformation: [
              {
                adjudicationOrPaymentDate: 'adjudicationOrPaymentDate',
                otherPayerPrimaryIdentifier: 'otherPayerPrimaryIdentifier',
                paidServiceUnitCount: 'paidServiceUnitCount',
                procedureCode: 'procedureCode',
                serviceIdQualifier: 'ER',
                serviceLinePaidAmount: 'serviceLinePaidAmount',
                bundledOrUnbundledLineNumber: 'bundledOrUnbundledLineNumber',
                claimAdjustmentInformation: [
                  {
                    adjustmentDetails: [
                      {
                        adjustmentAmount: 'adjustmentAmount',
                        adjustmentReasonCode: 'adjustmentReasonCode',
                        adjustmentQuantity: 'adjustmentQuantity',
                      },
                    ],
                    adjustmentGroupCode: 'CO',
                  },
                ],
                procedureCodeDescription: 'procedureCodeDescription',
                procedureModifier: ['string'],
                remainingPatientLiability: 'remainingPatientLiability',
              },
            ],
            linePricingRepricingInformation: {
              pricingMethodologyCode: '01',
              repricedAllowedAmount: '1',
              exceptionCode: '1',
              policyComplianceCode: '1',
              rejectReasonCode: 'T1',
              repricedApprovedAmbulatoryPatientGroupAmount: 'repricedApprovedAmbulatoryPatientGroupAmount',
              repricedApprovedAmbulatoryPatientGroupCode: 'repricedApprovedAmbulatoryPatientGroupCode',
              repricedSavingAmount: 'repricedSavingAmount',
              repricingOrganizationIdentifier: 'repricingOrganizationIdentifier',
              repricingPerDiemOrFlatRateAmount: 'repricingPerDiemOrFlatRateAmount',
            },
            obstetricAnesthesiaAdditionalUnits: 0,
            orderingProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            postageTaxAmount: 'postageTaxAmount',
            providerControlNumber: 'providerControlNumber',
            purchasedServiceInformation: {
              purchasedServiceChargeAmount: '10',
              purchasedServiceProviderIdentifier: '01',
            },
            purchasedServiceProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            referringProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            renderingProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            salesTaxAmount: 'salesTaxAmount',
            serviceDateEnd: 'serviceDateEnd',
            serviceFacilityLocation: {
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              organizationName: 'HAPPY DOCTORS GROUP',
              npi: 'npi',
              phoneExtension: 'phoneExtension',
              phoneName: 'phoneName',
              phoneNumber: 'phoneNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
            },
            serviceLineDateInformation: {
              beginTherapyDate: 'beginTherapyDate',
              certificationRevisionOrRecertificationDate: 'certificationRevisionOrRecertificationDate',
              hemoglobinTestDate: 'hemoglobinTestDate',
              initialTreatmentDate: 'initialTreatmentDate',
              lastCertificationDate: 'lastCertificationDate',
              lastXRayDate: 'lastXRayDate',
              prescriptionDate: 'prescriptionDate',
              serumCreatineTestDate: 'serumCreatineTestDate',
              shippedDate: 'shippedDate',
              treatmentOrTherapyDate: 'treatmentOrTherapyDate',
            },
            serviceLineReferenceInformation: {
              adjustedRepricedLineItemReferenceNumber: 'adjustedRepricedLineItemReferenceNumber',
              clinicalLaboratoryImprovementAmendmentNumber: 'clinicalLaboratoryImprovementAmendmentNumber',
              immunizationBatchNumber: 'immunizationBatchNumber',
              mammographyCertificationNumber: 'mammographyCertificationNumber',
              priorAuthorization: [
                {
                  priorAuthorizationOrReferralNumber: 'priorAuthorizationOrReferralNumber',
                  otherPayerPrimaryIdentifier: 'otherPayerPrimaryIdentifier',
                },
              ],
              referralNumber: ['string'],
              referringCliaNumber: 'referringCliaNumber',
              repricedLineItemReferenceNumber: 'repricedLineItemReferenceNumber',
            },
            serviceLineSupplementalInformation: [
              {
                attachmentReportTypeCode: '03',
                attachmentTransmissionCode: 'AA',
                attachmentControlNumber: 'attachmentControlNumber',
              },
            ],
            supervisingProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            testResults: [
              {
                measurementQualifier: 'HT',
                measurementReferenceIdentificationCode: 'OG',
                testResults: 'testResults',
              },
            ],
            thirdPartyOrganizationNotes: 'thirdPartyOrganizationNotes',
          },
        ],
        signatureIndicator: 'Y',
        ambulanceCertification: [{ certificationConditionIndicator: 'N', conditionCodes: ['01'] }],
        ambulanceDropOffLocation: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        ambulancePickUpLocation: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        ambulanceTransportInformation: {
          ambulanceTransportReasonCode: 'A',
          transportDistanceInMiles: 'transportDistanceInMiles',
          patientWeightInPounds: 'patientWeightInPounds',
          roundTripPurposeDescription: 'roundTripPurposeDescription',
          stretcherPurposeDescription: 'stretcherPurposeDescription',
        },
        anesthesiaRelatedSurgicalProcedure: ['string'],
        autoAccidentCountryCode: 'autoAccidentCountryCode',
        autoAccidentStateCode: 'AA',
        claimContractInformation: {
          contractTypeCode: '01',
          contractAmount: 'contractAmount',
          contractCode: 'contractCode',
          contractPercentage: 'contractPercentage',
          contractVersionIdentifier: 'contractVersionIdentifier',
          termsDiscountPercentage: 'termsDiscountPercentage',
        },
        claimDateInformation: {
          accidentDate: 'accidentDate',
          acuteManifestationDate: 'acuteManifestationDate',
          admissionDate: 'admissionDate',
          assumedAndRelinquishedCareBeginDate: 'assumedAndRelinquishedCareBeginDate',
          assumedAndRelinquishedCareEndDate: 'assumedAndRelinquishedCareEndDate',
          authorizedReturnToWorkDate: 'authorizedReturnToWorkDate',
          disabilityBeginDate: 'disabilityBeginDate',
          disabilityEndDate: 'disabilityEndDate',
          dischargeDate: 'dischargeDate',
          firstContactDate: 'firstContactDate',
          hearingAndVisionPrescriptionDate: 'hearingAndVisionPrescriptionDate',
          initialTreatmentDate: 'initialTreatmentDate',
          lastMenstrualPeriodDate: 'lastMenstrualPeriodDate',
          lastSeenDate: 'lastSeenDate',
          lastWorkedDate: 'lastWorkedDate',
          lastXRayDate: 'lastXRayDate',
          repricerReceivedDate: 'repricerReceivedDate',
          symptomDate: 'symptomDate',
        },
        claimNote: {
          additionalInformation: 'additionalInformation',
          certificationNarrative: 'certificationNarrative',
          diagnosisDescription: 'diagnosisDescription',
          goalRehabOrDischargePlans: 'goalRehabOrDischargePlans',
          thirdPartOrgNotes: 'thirdPartOrgNotes',
        },
        claimPricingRepricingInformation: {
          pricingMethodologyCode: '01',
          repricedAllowedAmount: '1',
          exceptionCode: '1',
          policyComplianceCode: '1',
          rejectReasonCode: 'T1',
          repricedApprovedAmbulatoryPatientGroupAmount: 'repricedApprovedAmbulatoryPatientGroupAmount',
          repricedApprovedAmbulatoryPatientGroupCode: 'repricedApprovedAmbulatoryPatientGroupCode',
          repricedSavingAmount: 'repricedSavingAmount',
          repricingOrganizationIdentifier: 'repricingOrganizationIdentifier',
          repricingPerDiemOrFlatRateAmount: 'repricingPerDiemOrFlatRateAmount',
        },
        claimSupplementalInformation: {
          adjustedRepricedClaimNumber: 'adjustedRepricedClaimNumber',
          carePlanOversightNumber: 'carePlanOversightNumber',
          claimControlNumber: 'claimControlNumber',
          claimNumber: '12345',
          cliaNumber: 'cliaNumber',
          demoProjectIdentifier: 'demoProjectIdentifier',
          investigationalDeviceExemptionNumber: 'investigationalDeviceExemptionNumber',
          mammographyCertificationNumber: 'mammographyCertificationNumber',
          medicalRecordNumber: 'medicalRecordNumber',
          medicareCrossoverReferenceId: 'medicareCrossoverReferenceId',
          priorAuthorizationNumber: 'priorAuthorizationNumber',
          referralNumber: 'referralNumber',
          reportInformation: {
            attachmentReportTypeCode: '03',
            attachmentTransmissionCode: 'AA',
            attachmentControlNumber: 'attachmentControlNumber',
          },
          repricedClaimNumber: '00001',
          serviceAuthorizationExceptionCode: '1',
        },
        conditionInformation: [{ conditionCodes: ['string'] }],
        deathDate: 'deathDate',
        delayReasonCode: '1',
        epsdtReferral: { certificationConditionCodeAppliesIndicator: 'N', conditionCodes: ['AV'] },
        fileInformation: 'fileInformation',
        fileInformationList: ['string'],
        homeboundIndicator: true,
        otherSubscriberInformation: [
          {
            benefitsAssignmentCertificationIndicator: 'N',
            claimFilingIndicatorCode: '11',
            individualRelationshipCode: '01',
            otherPayerName: {
              otherPayerIdentifier: 'otherPayerIdentifier',
              otherPayerIdentifierTypeCode: 'PI',
              otherPayerOrganizationName: 'otherPayerOrganizationName',
              otherInsuredAdditionalIdentifier: 'otherInsuredAdditionalIdentifier',
              otherPayerAddress: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              otherPayerAdjudicationOrPaymentDate: 'otherPayerAdjudicationOrPaymentDate',
              otherPayerClaimAdjustmentIndicator: true,
              otherPayerClaimControlNumber: 'otherPayerClaimControlNumber',
              otherPayerPriorAuthorizationNumber: 'otherPayerPriorAuthorizationNumber',
              otherPayerPriorAuthorizationOrReferralNumber: 'otherPayerPriorAuthorizationOrReferralNumber',
              otherPayerSecondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
            },
            otherSubscriberName: {
              otherInsuredIdentifier: 'otherInsuredIdentifier',
              otherInsuredIdentifierTypeCode: 'II',
              otherInsuredLastName: 'otherInsuredLastName',
              otherInsuredQualifier: '1',
              otherInsuredAdditionalIdentifier: 'otherInsuredAdditionalIdentifier',
              otherInsuredAddress: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              otherInsuredFirstName: 'otherInsuredFirstName',
              otherInsuredMiddleName: 'otherInsuredMiddleName',
              otherInsuredNameSuffix: 'otherInsuredNameSuffix',
            },
            paymentResponsibilityLevelCode: 'A',
            releaseOfInformationCode: 'I',
            claimLevelAdjustments: [
              {
                adjustmentDetails: [
                  {
                    adjustmentAmount: 'adjustmentAmount',
                    adjustmentReasonCode: 'adjustmentReasonCode',
                    adjustmentQuantity: 'adjustmentQuantity',
                  },
                ],
                adjustmentGroupCode: 'CO',
              },
            ],
            insuranceGroupOrPolicyNumber: 'insuranceGroupOrPolicyNumber',
            insuranceTypeCode: '12',
            medicareOutpatientAdjudication: {
              claimPaymentRemarkCode: ['string'],
              endStageRenalDiseasePaymentAmount: 'endStageRenalDiseasePaymentAmount',
              hcpcsPayableAmount: 'hcpcsPayableAmount',
              nonPayableProfessionalComponentBilledAmount: 'nonPayableProfessionalComponentBilledAmount',
              reimbursementRate: 'reimbursementRate',
            },
            nonCoveredChargeAmount: 'nonCoveredChargeAmount',
            otherInsuredGroupName: 'otherInsuredGroupName',
            otherPayerBillingProvider: [
              {
                entityTypeQualifier: '1',
                otherPayerBillingProviderIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerReferringProvider: [
              {
                otherPayerReferringProviderIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerRenderingProvider: [
              {
                entityTypeQualifier: '1',
                otherPayerRenderingProviderSecondaryIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerServiceFacilityLocation: [
              {
                otherPayerServiceFacilityLocationSecondaryIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerSupervisingProvider: [
              {
                otherPayerSupervisingProviderIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            patientSignatureGeneratedForPatient: true,
            payerPaidAmount: 'payerPaidAmount',
            remainingPatientLiability: 'remainingPatientLiability',
          },
        ],
        patientAmountPaid: 'patientAmountPaid',
        patientConditionInformationVision: [
          { certificationConditionIndicator: 'N', codeCategory: 'E1', conditionCodes: ['L1'] },
        ],
        patientSignatureSourceCode: false,
        patientWeight: 'patientWeight',
        pregnancyIndicator: 'Y',
        propertyCasualtyClaimNumber: 'propertyCasualtyClaimNumber',
        relatedCausesCode: ['AA'],
        serviceFacilityLocation: {
          address: {
            address1: '123 address1',
            city: 'city1',
            address2: 'apt 000',
            countryCode: 'countryCode',
            countrySubDivisionCode: 'countrySubDivisionCode',
            postalCode: '981010000',
            state: 'wa',
          },
          organizationName: 'HAPPY DOCTORS GROUP',
          npi: 'npi',
          phoneExtension: 'phoneExtension',
          phoneName: 'phoneName',
          phoneNumber: 'phoneNumber',
          secondaryIdentifier: [
            { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
          ],
        },
        specialProgramCode: '02',
        spinalManipulationServiceInformation: {
          patientConditionCode: 'patientConditionCode',
          patientConditionDescription1: 'A',
          patientConditionDescription2: 'patientConditionDescription2',
        },
      },
      controlNumber: '000000001',
      receiver: { organizationName: 'EXTRA HEALTHY INSURANCE' },
      submitter: {
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        firstName: 'janeone',
        lastName: 'doeOne',
        middleName: 'middleone',
        organizationName: 'REGIONAL PPO NETWORK',
      },
      subscriber: {
        paymentResponsibilityLevelCode: 'P',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        dateOfBirth: '19800102',
        firstName: 'johnone',
        gender: 'M',
        groupNumber: 'groupNumber',
        insuranceTypeCode: '12',
        lastName: 'doeOne',
        memberId: '0000000001',
        middleName: 'middleName',
        organizationName: 'organizationName',
        policyNumber: '00001',
        ssn: 'ssn',
        subscriberGroupName: 'Subscriber Group Name',
        suffix: 'Jr',
      },
      dependent: {
        dateOfBirth: '19800102',
        firstName: 'janeone',
        gender: 'F',
        lastName: 'doeOne',
        relationshipToSubscriberCode: '01',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        memberId: '19800102',
        middleName: 'middleName',
        ssn: '19800102',
        suffix: 'Jr',
      },
      ordering: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      payerAddress: {
        address1: '123 address1',
        city: 'city1',
        address2: 'apt 000',
        countryCode: 'countryCode',
        countrySubDivisionCode: 'countrySubDivisionCode',
        postalCode: '981010000',
        state: 'wa',
      },
      payToAddress: {
        address1: '123 address1',
        city: 'city1',
        address2: 'apt 000',
        countryCode: 'countryCode',
        countrySubDivisionCode: 'countrySubDivisionCode',
        postalCode: '981010000',
        state: 'wa',
      },
      payToPlan: {
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        organizationName: 'Example Org',
        primaryIdentifier: 'primaryIdentifier',
        primaryIdentifierTypeCode: 'PI',
        taxIdentificationNumber: 'taxIdentificationNumber',
        secondaryIdentifier: '11',
        secondaryIdentifierTypeCode: '2U',
      },
      providers: [
        {
          providerType: 'BillingProvider',
          address: {
            address1: '123 address1',
            city: 'city1',
            address2: 'apt 000',
            countryCode: 'countryCode',
            countrySubDivisionCode: 'countrySubDivisionCode',
            postalCode: '981010000',
            state: 'wa',
          },
          claimOfficeNumber: 'claimOfficeNumber',
          commercialNumber: 'commercialNumber',
          contactInformation: {
            name: 'SUBMITTER CONTACT INFO',
            email: 'email@email.com',
            faxNumber: '5551234567',
            phoneExtension: '1234',
            phoneNumber: '5554567890',
          },
          employerId: '123456789',
          employerIdentificationNumber: 'employerIdentificationNumber',
          firstName: 'johnone',
          lastName: 'doeone',
          locationNumber: 'locationNumber',
          middleName: 'middleone',
          naic: 'naic',
          npi: '1760854442',
          organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
          payerIdentificationNumber: 'payerIdentificationNumber',
          providerUpinNumber: 'providerUpinNumber',
          ssn: '000000000',
          stateLicenseNumber: 'stateLicenseNumber',
          suffix: 'Jr',
          taxonomyCode: 'taxonomyCode',
        },
      ],
      referring: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      rendering: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      supervising: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      tradingPartnerName: 'tradingPartnerName',
      tradingPartnerServiceId: '9496',
      usageIndicator: 'T',
      'x-chng-trace-id': 'x-chng-trace-id',
    });
  });

  // Prism tests are disabled
  test.skip('submitRawX12Claim', async () => {
    const responsePromise = client.medicalnetwork.professionalclaims.v3.submitRawX12Claim({});
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('validateClaim: only required params', async () => {
    const responsePromise = client.medicalnetwork.professionalclaims.v3.validateClaim({
      billing: { providerType: 'BillingProvider' },
      claimInformation: {
        benefitsAssignmentCertificationIndicator: 'Y',
        claimChargeAmount: '28.75',
        claimFilingCode: 'CI',
        claimFrequencyCode: '1',
        healthCareCodeInformation: [{ diagnosisCode: 'diagnosisCode', diagnosisTypeCode: 'BK' }],
        patientControlNumber: '12345',
        placeOfServiceCode: '11',
        planParticipationCode: 'A',
        releaseInformationCode: 'Y',
        serviceLines: [
          {
            professionalService: {
              compositeDiagnosisCodePointers: { diagnosisCodePointers: ['string'] },
              lineItemChargeAmount: '25',
              measurementUnit: 'UN',
              procedureCode: 'E0570',
              procedureIdentifier: 'HC',
              serviceUnitCount: '1',
            },
            serviceDate: '20050514',
          },
        ],
        signatureIndicator: 'Y',
      },
      controlNumber: '000000001',
      receiver: { organizationName: 'EXTRA HEALTHY INSURANCE' },
      submitter: { contactInformation: { name: 'SUBMITTER CONTACT INFO' } },
      subscriber: { paymentResponsibilityLevelCode: 'P' },
    });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  // Prism tests are disabled
  test.skip('validateClaim: required and optional params', async () => {
    const response = await client.medicalnetwork.professionalclaims.v3.validateClaim({
      billing: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      claimInformation: {
        benefitsAssignmentCertificationIndicator: 'Y',
        claimChargeAmount: '28.75',
        claimFilingCode: 'CI',
        claimFrequencyCode: '1',
        healthCareCodeInformation: [{ diagnosisCode: 'diagnosisCode', diagnosisTypeCode: 'BK' }],
        patientControlNumber: '12345',
        placeOfServiceCode: '11',
        planParticipationCode: 'A',
        releaseInformationCode: 'Y',
        serviceLines: [
          {
            professionalService: {
              compositeDiagnosisCodePointers: { diagnosisCodePointers: ['string'] },
              lineItemChargeAmount: '25',
              measurementUnit: 'UN',
              procedureCode: 'E0570',
              procedureIdentifier: 'HC',
              serviceUnitCount: '1',
              copayStatusCode: '0',
              description: 'description',
              emergencyIndicator: 'Y',
              epsdtIndicator: 'Y',
              familyPlanningIndicator: 'Y',
              placeOfServiceCode: 'placeOfServiceCode',
              procedureModifiers: ['string'],
            },
            serviceDate: '20050514',
            additionalNotes: 'additionalNotes',
            ambulanceCertification: [{ certificationConditionIndicator: 'N', conditionCodes: ['01'] }],
            ambulanceDropOffLocation: {
              address1: '123 address1',
              city: 'city1',
              address2: 'apt 000',
              countryCode: 'countryCode',
              countrySubDivisionCode: 'countrySubDivisionCode',
              postalCode: '981010000',
              state: 'wa',
            },
            ambulancePatientCount: 0,
            ambulancePickUpLocation: {
              address1: '123 address1',
              city: 'city1',
              address2: 'apt 000',
              countryCode: 'countryCode',
              countrySubDivisionCode: 'countrySubDivisionCode',
              postalCode: '981010000',
              state: 'wa',
            },
            ambulanceTransportInformation: {
              ambulanceTransportReasonCode: 'A',
              transportDistanceInMiles: 'transportDistanceInMiles',
              patientWeightInPounds: 'patientWeightInPounds',
              roundTripPurposeDescription: 'roundTripPurposeDescription',
              stretcherPurposeDescription: 'stretcherPurposeDescription',
            },
            assignedNumber: 'assignedNumber',
            conditionIndicatorDurableMedicalEquipment: {
              certificationConditionIndicator: 'Y',
              conditionIndicator: '38',
              conditionIndicatorCode: '38',
            },
            contractInformation: {
              contractTypeCode: '01',
              contractAmount: 'contractAmount',
              contractCode: 'contractCode',
              contractPercentage: 'contractPercentage',
              contractVersionIdentifier: 'contractVersionIdentifier',
              termsDiscountPercentage: 'termsDiscountPercentage',
            },
            drugIdentification: {
              measurementUnitCode: 'F2',
              nationalDrugCode: 'nationalDrugCode',
              nationalDrugUnitCount: 'nationalDrugUnitCount',
              serviceIdQualifier: 'EN',
              linkSequenceNumber: 'linkSequenceNumber',
              pharmacyPrescriptionNumber: 'pharmacyPrescriptionNumber',
            },
            durableMedicalEquipmentCertificateOfMedicalNecessity: { attachmentTransmissionCode: 'AB' },
            durableMedicalEquipmentCertification: {
              certificationTypeCode: 'I',
              durableMedicalEquipmentDurationInMonths: 'durableMedicalEquipmentDurationInMonths',
            },
            durableMedicalEquipmentService: {
              days: 'days',
              frequencyCode: '1',
              purchasePrice: 'purchasePrice',
              rentalPrice: 'rentalPrice',
            },
            fileInformation: ['string'],
            formIdentification: [
              {
                formIdentifier: 'formIdentifier',
                formTypeCode: 'AS',
                supportingDocumentation: [
                  {
                    questionNumber: 'questionNumber',
                    questionResponse: 'questionResponse',
                    questionResponseAsDate: 'questionResponseAsDate',
                    questionResponseAsPercent: 'questionResponseAsPercent',
                    questionResponseCode: 'N',
                  },
                ],
              },
            ],
            goalRehabOrDischargePlans: 'goalRehabOrDischargePlans',
            hospiceEmployeeIndicator: true,
            lineAdjudicationInformation: [
              {
                adjudicationOrPaymentDate: 'adjudicationOrPaymentDate',
                otherPayerPrimaryIdentifier: 'otherPayerPrimaryIdentifier',
                paidServiceUnitCount: 'paidServiceUnitCount',
                procedureCode: 'procedureCode',
                serviceIdQualifier: 'ER',
                serviceLinePaidAmount: 'serviceLinePaidAmount',
                bundledOrUnbundledLineNumber: 'bundledOrUnbundledLineNumber',
                claimAdjustmentInformation: [
                  {
                    adjustmentDetails: [
                      {
                        adjustmentAmount: 'adjustmentAmount',
                        adjustmentReasonCode: 'adjustmentReasonCode',
                        adjustmentQuantity: 'adjustmentQuantity',
                      },
                    ],
                    adjustmentGroupCode: 'CO',
                  },
                ],
                procedureCodeDescription: 'procedureCodeDescription',
                procedureModifier: ['string'],
                remainingPatientLiability: 'remainingPatientLiability',
              },
            ],
            linePricingRepricingInformation: {
              pricingMethodologyCode: '01',
              repricedAllowedAmount: '1',
              exceptionCode: '1',
              policyComplianceCode: '1',
              rejectReasonCode: 'T1',
              repricedApprovedAmbulatoryPatientGroupAmount: 'repricedApprovedAmbulatoryPatientGroupAmount',
              repricedApprovedAmbulatoryPatientGroupCode: 'repricedApprovedAmbulatoryPatientGroupCode',
              repricedSavingAmount: 'repricedSavingAmount',
              repricingOrganizationIdentifier: 'repricingOrganizationIdentifier',
              repricingPerDiemOrFlatRateAmount: 'repricingPerDiemOrFlatRateAmount',
            },
            obstetricAnesthesiaAdditionalUnits: 0,
            orderingProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            postageTaxAmount: 'postageTaxAmount',
            providerControlNumber: 'providerControlNumber',
            purchasedServiceInformation: {
              purchasedServiceChargeAmount: '10',
              purchasedServiceProviderIdentifier: '01',
            },
            purchasedServiceProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            referringProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            renderingProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            salesTaxAmount: 'salesTaxAmount',
            serviceDateEnd: 'serviceDateEnd',
            serviceFacilityLocation: {
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              organizationName: 'HAPPY DOCTORS GROUP',
              npi: 'npi',
              phoneExtension: 'phoneExtension',
              phoneName: 'phoneName',
              phoneNumber: 'phoneNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
            },
            serviceLineDateInformation: {
              beginTherapyDate: 'beginTherapyDate',
              certificationRevisionOrRecertificationDate: 'certificationRevisionOrRecertificationDate',
              hemoglobinTestDate: 'hemoglobinTestDate',
              initialTreatmentDate: 'initialTreatmentDate',
              lastCertificationDate: 'lastCertificationDate',
              lastXRayDate: 'lastXRayDate',
              prescriptionDate: 'prescriptionDate',
              serumCreatineTestDate: 'serumCreatineTestDate',
              shippedDate: 'shippedDate',
              treatmentOrTherapyDate: 'treatmentOrTherapyDate',
            },
            serviceLineReferenceInformation: {
              adjustedRepricedLineItemReferenceNumber: 'adjustedRepricedLineItemReferenceNumber',
              clinicalLaboratoryImprovementAmendmentNumber: 'clinicalLaboratoryImprovementAmendmentNumber',
              immunizationBatchNumber: 'immunizationBatchNumber',
              mammographyCertificationNumber: 'mammographyCertificationNumber',
              priorAuthorization: [
                {
                  priorAuthorizationOrReferralNumber: 'priorAuthorizationOrReferralNumber',
                  otherPayerPrimaryIdentifier: 'otherPayerPrimaryIdentifier',
                },
              ],
              referralNumber: ['string'],
              referringCliaNumber: 'referringCliaNumber',
              repricedLineItemReferenceNumber: 'repricedLineItemReferenceNumber',
            },
            serviceLineSupplementalInformation: [
              {
                attachmentReportTypeCode: '03',
                attachmentTransmissionCode: 'AA',
                attachmentControlNumber: 'attachmentControlNumber',
              },
            ],
            supervisingProvider: {
              providerType: 'BillingProvider',
              address: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              claimOfficeNumber: 'claimOfficeNumber',
              commercialNumber: 'commercialNumber',
              contactInformation: {
                name: 'SUBMITTER CONTACT INFO',
                email: 'email@email.com',
                faxNumber: '5551234567',
                phoneExtension: '1234',
                phoneNumber: '5554567890',
              },
              employerId: '123456789',
              employerIdentificationNumber: 'employerIdentificationNumber',
              firstName: 'johnone',
              lastName: 'doeone',
              locationNumber: 'locationNumber',
              middleName: 'middleone',
              naic: 'naic',
              npi: '1760854442',
              organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
              otherIdentifier: 'otherIdentifier',
              payerIdentificationNumber: 'payerIdentificationNumber',
              providerUpinNumber: 'providerUpinNumber',
              secondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
              ssn: '000000000',
              stateLicenseNumber: 'stateLicenseNumber',
              suffix: 'Jr',
              taxonomyCode: 'taxonomyCode',
            },
            testResults: [
              {
                measurementQualifier: 'HT',
                measurementReferenceIdentificationCode: 'OG',
                testResults: 'testResults',
              },
            ],
            thirdPartyOrganizationNotes: 'thirdPartyOrganizationNotes',
          },
        ],
        signatureIndicator: 'Y',
        ambulanceCertification: [{ certificationConditionIndicator: 'N', conditionCodes: ['01'] }],
        ambulanceDropOffLocation: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        ambulancePickUpLocation: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        ambulanceTransportInformation: {
          ambulanceTransportReasonCode: 'A',
          transportDistanceInMiles: 'transportDistanceInMiles',
          patientWeightInPounds: 'patientWeightInPounds',
          roundTripPurposeDescription: 'roundTripPurposeDescription',
          stretcherPurposeDescription: 'stretcherPurposeDescription',
        },
        anesthesiaRelatedSurgicalProcedure: ['string'],
        autoAccidentCountryCode: 'autoAccidentCountryCode',
        autoAccidentStateCode: 'AA',
        claimContractInformation: {
          contractTypeCode: '01',
          contractAmount: 'contractAmount',
          contractCode: 'contractCode',
          contractPercentage: 'contractPercentage',
          contractVersionIdentifier: 'contractVersionIdentifier',
          termsDiscountPercentage: 'termsDiscountPercentage',
        },
        claimDateInformation: {
          accidentDate: 'accidentDate',
          acuteManifestationDate: 'acuteManifestationDate',
          admissionDate: 'admissionDate',
          assumedAndRelinquishedCareBeginDate: 'assumedAndRelinquishedCareBeginDate',
          assumedAndRelinquishedCareEndDate: 'assumedAndRelinquishedCareEndDate',
          authorizedReturnToWorkDate: 'authorizedReturnToWorkDate',
          disabilityBeginDate: 'disabilityBeginDate',
          disabilityEndDate: 'disabilityEndDate',
          dischargeDate: 'dischargeDate',
          firstContactDate: 'firstContactDate',
          hearingAndVisionPrescriptionDate: 'hearingAndVisionPrescriptionDate',
          initialTreatmentDate: 'initialTreatmentDate',
          lastMenstrualPeriodDate: 'lastMenstrualPeriodDate',
          lastSeenDate: 'lastSeenDate',
          lastWorkedDate: 'lastWorkedDate',
          lastXRayDate: 'lastXRayDate',
          repricerReceivedDate: 'repricerReceivedDate',
          symptomDate: 'symptomDate',
        },
        claimNote: {
          additionalInformation: 'additionalInformation',
          certificationNarrative: 'certificationNarrative',
          diagnosisDescription: 'diagnosisDescription',
          goalRehabOrDischargePlans: 'goalRehabOrDischargePlans',
          thirdPartOrgNotes: 'thirdPartOrgNotes',
        },
        claimPricingRepricingInformation: {
          pricingMethodologyCode: '01',
          repricedAllowedAmount: '1',
          exceptionCode: '1',
          policyComplianceCode: '1',
          rejectReasonCode: 'T1',
          repricedApprovedAmbulatoryPatientGroupAmount: 'repricedApprovedAmbulatoryPatientGroupAmount',
          repricedApprovedAmbulatoryPatientGroupCode: 'repricedApprovedAmbulatoryPatientGroupCode',
          repricedSavingAmount: 'repricedSavingAmount',
          repricingOrganizationIdentifier: 'repricingOrganizationIdentifier',
          repricingPerDiemOrFlatRateAmount: 'repricingPerDiemOrFlatRateAmount',
        },
        claimSupplementalInformation: {
          adjustedRepricedClaimNumber: 'adjustedRepricedClaimNumber',
          carePlanOversightNumber: 'carePlanOversightNumber',
          claimControlNumber: 'claimControlNumber',
          claimNumber: '12345',
          cliaNumber: 'cliaNumber',
          demoProjectIdentifier: 'demoProjectIdentifier',
          investigationalDeviceExemptionNumber: 'investigationalDeviceExemptionNumber',
          mammographyCertificationNumber: 'mammographyCertificationNumber',
          medicalRecordNumber: 'medicalRecordNumber',
          medicareCrossoverReferenceId: 'medicareCrossoverReferenceId',
          priorAuthorizationNumber: 'priorAuthorizationNumber',
          referralNumber: 'referralNumber',
          reportInformation: {
            attachmentReportTypeCode: '03',
            attachmentTransmissionCode: 'AA',
            attachmentControlNumber: 'attachmentControlNumber',
          },
          repricedClaimNumber: '00001',
          serviceAuthorizationExceptionCode: '1',
        },
        conditionInformation: [{ conditionCodes: ['string'] }],
        deathDate: 'deathDate',
        delayReasonCode: '1',
        epsdtReferral: { certificationConditionCodeAppliesIndicator: 'N', conditionCodes: ['AV'] },
        fileInformation: 'fileInformation',
        fileInformationList: ['string'],
        homeboundIndicator: true,
        otherSubscriberInformation: [
          {
            benefitsAssignmentCertificationIndicator: 'N',
            claimFilingIndicatorCode: '11',
            individualRelationshipCode: '01',
            otherPayerName: {
              otherPayerIdentifier: 'otherPayerIdentifier',
              otherPayerIdentifierTypeCode: 'PI',
              otherPayerOrganizationName: 'otherPayerOrganizationName',
              otherInsuredAdditionalIdentifier: 'otherInsuredAdditionalIdentifier',
              otherPayerAddress: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              otherPayerAdjudicationOrPaymentDate: 'otherPayerAdjudicationOrPaymentDate',
              otherPayerClaimAdjustmentIndicator: true,
              otherPayerClaimControlNumber: 'otherPayerClaimControlNumber',
              otherPayerPriorAuthorizationNumber: 'otherPayerPriorAuthorizationNumber',
              otherPayerPriorAuthorizationOrReferralNumber: 'otherPayerPriorAuthorizationOrReferralNumber',
              otherPayerSecondaryIdentifier: [
                { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
              ],
            },
            otherSubscriberName: {
              otherInsuredIdentifier: 'otherInsuredIdentifier',
              otherInsuredIdentifierTypeCode: 'II',
              otherInsuredLastName: 'otherInsuredLastName',
              otherInsuredQualifier: '1',
              otherInsuredAdditionalIdentifier: 'otherInsuredAdditionalIdentifier',
              otherInsuredAddress: {
                address1: '123 address1',
                city: 'city1',
                address2: 'apt 000',
                countryCode: 'countryCode',
                countrySubDivisionCode: 'countrySubDivisionCode',
                postalCode: '981010000',
                state: 'wa',
              },
              otherInsuredFirstName: 'otherInsuredFirstName',
              otherInsuredMiddleName: 'otherInsuredMiddleName',
              otherInsuredNameSuffix: 'otherInsuredNameSuffix',
            },
            paymentResponsibilityLevelCode: 'A',
            releaseOfInformationCode: 'I',
            claimLevelAdjustments: [
              {
                adjustmentDetails: [
                  {
                    adjustmentAmount: 'adjustmentAmount',
                    adjustmentReasonCode: 'adjustmentReasonCode',
                    adjustmentQuantity: 'adjustmentQuantity',
                  },
                ],
                adjustmentGroupCode: 'CO',
              },
            ],
            insuranceGroupOrPolicyNumber: 'insuranceGroupOrPolicyNumber',
            insuranceTypeCode: '12',
            medicareOutpatientAdjudication: {
              claimPaymentRemarkCode: ['string'],
              endStageRenalDiseasePaymentAmount: 'endStageRenalDiseasePaymentAmount',
              hcpcsPayableAmount: 'hcpcsPayableAmount',
              nonPayableProfessionalComponentBilledAmount: 'nonPayableProfessionalComponentBilledAmount',
              reimbursementRate: 'reimbursementRate',
            },
            nonCoveredChargeAmount: 'nonCoveredChargeAmount',
            otherInsuredGroupName: 'otherInsuredGroupName',
            otherPayerBillingProvider: [
              {
                entityTypeQualifier: '1',
                otherPayerBillingProviderIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerReferringProvider: [
              {
                otherPayerReferringProviderIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerRenderingProvider: [
              {
                entityTypeQualifier: '1',
                otherPayerRenderingProviderSecondaryIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerServiceFacilityLocation: [
              {
                otherPayerServiceFacilityLocationSecondaryIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            otherPayerSupervisingProvider: [
              {
                otherPayerSupervisingProviderIdentifier: [
                  { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
                ],
              },
            ],
            patientSignatureGeneratedForPatient: true,
            payerPaidAmount: 'payerPaidAmount',
            remainingPatientLiability: 'remainingPatientLiability',
          },
        ],
        patientAmountPaid: 'patientAmountPaid',
        patientConditionInformationVision: [
          { certificationConditionIndicator: 'N', codeCategory: 'E1', conditionCodes: ['L1'] },
        ],
        patientSignatureSourceCode: false,
        patientWeight: 'patientWeight',
        pregnancyIndicator: 'Y',
        propertyCasualtyClaimNumber: 'propertyCasualtyClaimNumber',
        relatedCausesCode: ['AA'],
        serviceFacilityLocation: {
          address: {
            address1: '123 address1',
            city: 'city1',
            address2: 'apt 000',
            countryCode: 'countryCode',
            countrySubDivisionCode: 'countrySubDivisionCode',
            postalCode: '981010000',
            state: 'wa',
          },
          organizationName: 'HAPPY DOCTORS GROUP',
          npi: 'npi',
          phoneExtension: 'phoneExtension',
          phoneName: 'phoneName',
          phoneNumber: 'phoneNumber',
          secondaryIdentifier: [
            { identifier: 'identifier', qualifier: 'qualifier', otherIdentifier: 'otherIdentifier' },
          ],
        },
        specialProgramCode: '02',
        spinalManipulationServiceInformation: {
          patientConditionCode: 'patientConditionCode',
          patientConditionDescription1: 'A',
          patientConditionDescription2: 'patientConditionDescription2',
        },
      },
      controlNumber: '000000001',
      receiver: { organizationName: 'EXTRA HEALTHY INSURANCE' },
      submitter: {
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        firstName: 'janeone',
        lastName: 'doeOne',
        middleName: 'middleone',
        organizationName: 'REGIONAL PPO NETWORK',
      },
      subscriber: {
        paymentResponsibilityLevelCode: 'P',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        dateOfBirth: '19800102',
        firstName: 'johnone',
        gender: 'M',
        groupNumber: 'groupNumber',
        insuranceTypeCode: '12',
        lastName: 'doeOne',
        memberId: '0000000001',
        middleName: 'middleName',
        organizationName: 'organizationName',
        policyNumber: '00001',
        ssn: 'ssn',
        subscriberGroupName: 'Subscriber Group Name',
        suffix: 'Jr',
      },
      dependent: {
        dateOfBirth: '19800102',
        firstName: 'janeone',
        gender: 'F',
        lastName: 'doeOne',
        relationshipToSubscriberCode: '01',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        memberId: '19800102',
        middleName: 'middleName',
        ssn: '19800102',
        suffix: 'Jr',
      },
      ordering: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      payerAddress: {
        address1: '123 address1',
        city: 'city1',
        address2: 'apt 000',
        countryCode: 'countryCode',
        countrySubDivisionCode: 'countrySubDivisionCode',
        postalCode: '981010000',
        state: 'wa',
      },
      payToAddress: {
        address1: '123 address1',
        city: 'city1',
        address2: 'apt 000',
        countryCode: 'countryCode',
        countrySubDivisionCode: 'countrySubDivisionCode',
        postalCode: '981010000',
        state: 'wa',
      },
      payToPlan: {
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        organizationName: 'Example Org',
        primaryIdentifier: 'primaryIdentifier',
        primaryIdentifierTypeCode: 'PI',
        taxIdentificationNumber: 'taxIdentificationNumber',
        secondaryIdentifier: '11',
        secondaryIdentifierTypeCode: '2U',
      },
      providers: [
        {
          providerType: 'BillingProvider',
          address: {
            address1: '123 address1',
            city: 'city1',
            address2: 'apt 000',
            countryCode: 'countryCode',
            countrySubDivisionCode: 'countrySubDivisionCode',
            postalCode: '981010000',
            state: 'wa',
          },
          claimOfficeNumber: 'claimOfficeNumber',
          commercialNumber: 'commercialNumber',
          contactInformation: {
            name: 'SUBMITTER CONTACT INFO',
            email: 'email@email.com',
            faxNumber: '5551234567',
            phoneExtension: '1234',
            phoneNumber: '5554567890',
          },
          employerId: '123456789',
          employerIdentificationNumber: 'employerIdentificationNumber',
          firstName: 'johnone',
          lastName: 'doeone',
          locationNumber: 'locationNumber',
          middleName: 'middleone',
          naic: 'naic',
          npi: '1760854442',
          organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
          payerIdentificationNumber: 'payerIdentificationNumber',
          providerUpinNumber: 'providerUpinNumber',
          ssn: '000000000',
          stateLicenseNumber: 'stateLicenseNumber',
          suffix: 'Jr',
          taxonomyCode: 'taxonomyCode',
        },
      ],
      referring: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      rendering: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      supervising: {
        providerType: 'BillingProvider',
        address: {
          address1: '123 address1',
          city: 'city1',
          address2: 'apt 000',
          countryCode: 'countryCode',
          countrySubDivisionCode: 'countrySubDivisionCode',
          postalCode: '981010000',
          state: 'wa',
        },
        claimOfficeNumber: 'claimOfficeNumber',
        commercialNumber: 'commercialNumber',
        contactInformation: {
          name: 'SUBMITTER CONTACT INFO',
          email: 'email@email.com',
          faxNumber: '5551234567',
          phoneExtension: '1234',
          phoneNumber: '5554567890',
        },
        employerId: '123456789',
        employerIdentificationNumber: 'employerIdentificationNumber',
        firstName: 'johnone',
        lastName: 'doeone',
        locationNumber: 'locationNumber',
        middleName: 'middleone',
        naic: 'naic',
        npi: '1760854442',
        organizationName: 'HAPPY DOCTORS GROUPPRACTICE',
        payerIdentificationNumber: 'payerIdentificationNumber',
        providerUpinNumber: 'providerUpinNumber',
        ssn: '000000000',
        stateLicenseNumber: 'stateLicenseNumber',
        suffix: 'Jr',
        taxonomyCode: 'taxonomyCode',
      },
      tradingPartnerName: 'tradingPartnerName',
      tradingPartnerServiceId: '9496',
      usageIndicator: 'T',
      'x-chng-trace-id': 'x-chng-trace-id',
    });
  });

  // Prism tests are disabled
  test.skip('validateRawX12Claim', async () => {
    const responsePromise = client.medicalnetwork.professionalclaims.v3.validateRawX12Claim({});
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });
});
